function 显示首次启动页(显示时是否使用动画)
  import "wenben"
  首次启动页布局=
  {
    FrameLayout;
    layout_width='fill';--布局宽度
    layout_height="fill";
    background=背景2,
    id='首次启动页FrameLayout';--布局高度
    {
      ScrollView;--线性布局
      layout_width='fill';--布局宽度
      layout_height='wrap';--布局高度
      id='用户协议和隐私政策';--布局高度
      {
        LinearLayout;
        layout_width='fill';--布局宽度
        layout_height="fill";
        orientation="vertical";
        {
          TextView;
          layout_width='wrap';
          layout_height='wrap';
          layout_margin='20dp';
          textColor='#FF000000';
          text="请阅读以下内容";
          id="标题";
          textSize='20sp';
          textColor=一般强调色;
          layout_gravity="center";
          gravity="center";
        };
        {
          LinearLayout;
          Elevation='-1';
          layout_width='fill';
          id='用户协议按钮';
          onClick=function()
            对话框({
              标题="用户协议",
              点击事件=function()end,
              文本内容=用户协议,
              是否显示取消按钮=false,
            })
          end,
          {
            TextView;
            -- layout_width='wrap';
            layout_height='fill';
            layout_marginLeft='25dp';
            layout_margin='16dp';
            Gravity='left|center';
            textColor=文字;
            text='用户协议';
            textSize='16sp';
          };
        };
        {
          LinearLayout;
          Elevation='-1';
          layout_width='fill';
          id='隐私政策按钮';
          layout_marginBottom="9dp";
          onClick=function()
            对话框({
              标题="隐私政策",
              点击事件=function()end,
              文本内容=隐私政策,
              是否显示取消按钮=false,
            })
          end,
          {
            TextView;
            -- layout_width='wrap';
            layout_height='fill';
            layout_marginLeft='25dp';
            layout_margin='16dp';
            Gravity='left|center';
            textColor=文字;
            text='隐私政策';
            textSize='16sp';
          };
        };
        {
          LinearLayout;
          layout_width='fill';--布局宽度
          orientation="vertical";
          layout_margin='18dp';
          backgroundDrawable=边框(圆角大小,"#00000000",边框2,dp2px("1.5"));
          layout_marginTop="0";
          Gravity='center';
          {
            TextView;
            layout_width='fill';
            layout_height='fill';
            padding='16dp';
            Gravity='center';
            textColor=文字;
            text='不同意以上内容';
            textSize='16sp';
            id='不同意按钮';
            onClick=function()
              activity.finish()
            end,
          };
        };
        {
          LinearLayout;
          layout_width='fill';--布局宽度
          orientation="vertical";
          layout_margin='18dp';
          backgroundDrawable=边框(圆角大小,"#00000000",边框2,dp2px("1.5"));
          layout_marginTop="0";
          Gravity='center';
          {
            TextView;
            layout_width='fill';
            layout_height='fill';
            padding='16dp';
            Gravity='center';
            textColor=文字;
            text='同意以上内容';
            textSize='16sp';
            id='同意按钮';
            onClick=function()
              关闭对话框a()
              写入文件("/data/data/"..activity.getPackageName().."/是否是首次启动.xml","打开")
              task(150,function()
                对话框({
                  标题="提示",
                  点击事件=function()
                    activity.newActivity('sts/st2')
                  end,
                  文本内容="是否进入设置？",
                  是否显示取消按钮=true,
                })
              end)
            end,
          };
        };
        {
          LinearLayout;
          layout_width='fill';--布局宽度
          orientation="vertical";
          layout_margin='18dp';
          backgroundDrawable=边框(圆角大小,"#00000000",边框2,dp2px("1.5"));
          layout_marginTop="0";
          id="源码";
          {
            TextView;
            layout_width="fill";
            id="内容TextView";
            textColor=文字;
            layout_height="fill";
            textSize="16sp";
            padding="25dp";
            text="这个APP在启动时即使显示的页面也不一定加载完了。";
            textIsSelectable=true,
          };
        };
        {
          LinearLayout;
          layout_width='fill';--布局宽度
          orientation="vertical";
          layout_margin='18dp';
          backgroundDrawable=边框(圆角大小,"#00000000",边框2,dp2px("1.5"));
          layout_marginTop="0";
          id="源码";
          {
            TextView;
            layout_width="fill";
            id="内容TextView2";
            textColor=文字;
            layout_height="fill";
            textSize="16sp";
            padding="25dp";
            text=[[滑动菜单使用教程:
1.把手按在右边的第1个小条上，就会显示主页项目，然后让手指在想用的功能松开，就可以访问那个主页项目的网页点击打开书签长按添加书签或主页项目。
2.右边的第2个小条像上面那样操作可可以使用常用工具，常用工具可以到设置里面的操作设置中的滑动菜单设置中的工具设置来更改。点击或长按会有像上面那样的效果。
3.点击右边的第3个按钮，可以打开菜单长按可以打开工具箱，下滑可以搜索。
4.点击右边的第4个按钮可以切换窗口，长按可新建窗口。
这几个按钮往右滑可以返回上一个网页。]];
            textIsSelectable=true,
          };
        };
        {
          LinearLayout;
          layout_width='fill';--布局宽度
          orientation="vertical";
          layout_margin='18dp';
          backgroundDrawable=边框(圆角大小,"#00000000",边框2,dp2px("1.5"));
          layout_marginTop="0";
          id="源码";
          {
            TextView;
            layout_width="fill";
            id="内容TextView";
            textColor=文字;
            layout_height="fill";
            textSize="16sp";
            padding="25dp";
            text="如果不想用滑动菜单的话，可以到操作设置找到滑动菜单设置里面把滑动菜单模式关掉。";
            textIsSelectable=true,
          };
        };
        {
          LinearLayout;
          layout_width='fill';--布局宽度
          orientation="vertical";
          layout_margin='18dp';
          backgroundDrawable=边框(圆角大小,"#00000000",边框2,dp2px("1.5"));
          layout_marginTop="0";
          id="源码";
          {
            TextView;
            layout_width="fill";
            id="内容TextView";
            textColor=文字;
            layout_height="fill";
            textSize="16sp";
            padding="25dp";
            paddingBottom="18dp";
            text="这个应用是开源的，要不要获取源码？源码也可以在关于里面获取。";
            textIsSelectable=true,
          };
          {
            LinearLayout;
            layout_gravity="end";
            {
              CardView;--卡片控件
              id="确定CardView";
              --  layout_gravity="right|bottom";
              CardElevation='4dp';--卡片阴影
              --adjustViewBounds=true,
              -- layout_margin="24dp",
              layout_width='-2';--卡片宽度
              layout_height='-2';--卡片高
              radius='4dp';--卡片圆角
              CardBackgroundColor=强调色;--卡片背景颜色--#F17F42
              -- Gravity="center",
              layout_marginRight="25dp";
              layout_marginTop="0";
              layout_marginBottom="25dp";
              {
                TextView;
                layout_width="fill";
                id="确定TextView";
                gravity="center";
                text="确定";
                textColor="#ffffff";
                layout_height="fill";
                textSize="14sp";
                --onClick=点击事件;
                paddingRight="16dp";
                paddingLeft="16dp";
                paddingTop="10dp";
                paddingBottom="10dp";
                onClick=function()
                  import "android.content.Intent"
                  import "android.net.Uri"
                  url="http://www.iyuji.cn/iyuji/s/RWlIQnNReFJrWmxONjREaWEvR2hBUT09/1580171453352562"
                  viewIntent = Intent("android.intent.action.VIEW",Uri.parse(url))
                  activity.startActivity(viewIntent)
                end,
              };
            };
          };
        };
      };
    };
  };
  popa=弹窗(loadlayout(首次启动页布局),false)
  import "android.view.animation.AlphaAnimation"
  是否在首次启动页=true
  function 关闭对话框a()
    关闭对话框b=关闭对话框
    --设置动画的属性
    透明动画=AlphaAnimation(1,0)
    透明动画.setDuration(67)--设置动画时间
    透明动画.setFillAfter(true)--设置动画后停留位置
    透明动画.setRepeatCount(0)--设置无限循环
    --绑定动画
    首次启动页FrameLayout.startAnimation(透明动画)
    task(100,function()
      popa.dismiss()
    end)
  end
  波纹({确定TextView,
    用户协议按钮,
    隐私政策按钮,
    不同意按钮,
    同意按钮,
    --进入主页TextView,
  },"方",文字)
  --设置加粗
  标题.getPaint().setFakeBoldText(true)
  --设置加粗
  确定TextView.getPaint().setFakeBoldText(true)
end