local gt2={
        LinearLayout,
        orientation="vertical",
        layout_height='fill';
        layout_width='fill';
        --gravity="bottom|center";
        id='idmlz外';
        {
          FrameLayout,
          layout_height='fill';
          layout_width='fill';
          id='idmlz';
          {
            FrameLayout,
            layout_height='fill';
            layout_width='fill';
            background=菜单背景,
            id='菜单背景FrameLayout';
          };
          {
            CardView;
            Elevation='8dp';
            layout_width='fill';
            radius='30dp';
            --layout_gravity="bottom|center";
            layout_marginTop='-30dp';
            id='菜单CardView';
            {
              LinearLayout;
              Orientation='vertical';
              layout_width='fill';
              --layout_height='420dp';
              layout_marginBottom='0dp';
              layout_marginTop="30dp";
              BackgroundColor=背景2;
              {
                LinearLayout;
                Orientation='vertical';
                layout_width='fill';
                {
                  LinearLayout,
                  layout_height="match_parent",
                  layout_width="match_parent",
                  orientation="vertical",
                  {
                    TextView;
                    layout_width="fill";
                    id="标题TextView";
                    textColor=文字;
                    textSize="18sp";
                    padding="18dp";
                    textIsSelectable=true,
                    background=较暗色2;
                    paddingBottom='0dp';
                  };
                  {
                    TextView;
                    textColor=文字qwe;
                    id='上链接TextView';
                    --Typeface=字体("Product");
                    padding='8dp';
                    paddingLeft="18dp";
                    layout_width="fill";
                    paddingTop="0";
                    background=较暗色2;
                    singleLine=true;--设置单行
                    --id='颜色设置提示文字';
                  };
                  {
                    GridView;
                    fastScrollEnabled=true;
                    layout_width="fill";
                    --background=背景2,
                    --padding="8dp";
                    clipToPadding=false;
                    ScrollBarStyle=ScrollView.SCROLLBARS_OUTSIDE_OVERLAY;
                    -- layout_height="40%w";--高度需要更苦list多少进行计算，或者自己根据自己的不同写表达式
                    --这里是分割线的意思
                    numColumns=4;--每排显示网格数
                    id="list3";
                    Gravity="center",
                    background=较暗色2;
                    paddingBottom='18dp';
                  };
                };
                {
                  TextView;
                  textColor=文字qwe;
                  text='当前链接';
                  --Typeface=字体("Product");
                  padding='8dp';
                  paddingLeft="18dp";
                  layout_width="fill";
                  --id='颜色设置提示文字';
                };
                {
                  TextView;
                  layout_width="fill";
                  id="链接TextView";
                  textColor=文字qwe;
                  layout_height="fill";
                  textSize="16sp";
                  padding="18dp";
                  paddingTop="0";
                  textIsSelectable=true,
                };

                {
                  TextView;
                  textColor=文字qwe;
                  text='网页域名';
                  --Typeface=字体("Product");
                  padding='8dp';
                  paddingLeft="18dp";
                  layout_width="fill";
                  --id='颜色设置提示文字';
                };
                {
                  TextView;
                  layout_width="fill";
                  id="域名TextView";
                  textColor=文字qwe;
                  layout_height="fill";
                  textSize="16sp";
                  padding="18dp";
                  paddingTop="0";
                  textIsSelectable=true,
                };
                {
                  FrameLayout,
                  --  Orientation='vertical';
                  layout_width='fill';
                  layout_height='44dp';
                  BackgroundColor=背景2;
                  {
                    LinearLayout;
                    Orientation='vertical';
                    layout_width='fill';
                    layout_height='44dp';
                    Gravity="center",
                    id="关闭";
                    -- onTouchListener=点击监听,--动画效果
                    {
                      ImageView;
                      layout_height="30dp";
                      src="png/kadb.png";
                      id="关闭图标";
                      ColorFilter=文字,--图片颜色
                      layout_width="30dp";
                    };
                  };
                  {
                    LinearLayout;
                    Orientation='horizontal';
                    layout_gravity='right|center';
                    id="右下角菜单";
                  };
                };
              };
            };
          };
        };
      };


      local dialog1=弹窗2(loadlayout(gt2))
    import "mods.fenxiang"
  --波纹(gfwz,0xffff0000)
      --波纹(hhbgvbg,0xffff0000)
      function 关闭对话框()
        yuxuandh4=TranslateAnimation(0,0,0,-h)
        yuxuandh4.setDuration(75)
        菜单CardView.startAnimation(yuxuandh4);
        import "android.view.animation.Animation$AnimationListener"
        yuxuandh4.setAnimationListener(AnimationListener{
          onAnimationEnd=function()
            return dialog1 and dialog1.dismiss()
        end})
        --设置动画的属性
        透明动画=AlphaAnimation(1,0)
        透明动画.setDuration(75)--设置动画时间
        透明动画.setFillAfter(true)--设置动画后停留位置
        透明动画.setRepeatCount(0)--设置无限循环
        --绑定动画
        菜单背景FrameLayout.startAnimation(透明动画)
      end
      isAnimaing = false
      dialog1.setOnKeyListener{
        onKey = function(dl,c,v)
          if c == 4 and v.getAction() == MotionEvent.ACTION_DOWN then
            if isAnimaing == false then
              isAnimaing = true
              --弹出消息("返回键")
              关闭对话框()
            end
            return true
          end

        end
      }
      关闭对话框b=关闭对话框
      关闭.onClick=function()
        关闭对话框()
      end
      idmlz.onClick=function()
        关闭对话框()
      end
      波纹({关闭,
      },"方",文字)--0xFF7F7F7F
      if view.Title then
        标题TextView.text=view.Title;
      end
      if view.Url then
        链接TextView.text=view.Url;
        上链接TextView.text=view.Url;
        域名TextView.text=Uri.parse(view.url).authority;
      end
      function 复制(内容)
        --先导入包
        import "android.content.*"
        activity.getSystemService(Context.CLIPBOARD_SERVICE).setText(内容)
        print("已复制")
      end
      --设置加粗
      标题TextView.getPaint().setFakeBoldText(true)
      标题TextView.onClick=function(v)
        复制(view.Title)
      end
      标题TextView.onLongClick=function(v)
        复制(view.Title)
      end
      链接TextView.onClick=function(v)
        复制(view.Url)
      end
      链接TextView.onLongClick=function(v)
        复制(view.Url)
      end
      域名TextView.onClick=function(v)
        复制(Uri.parse(view.url).authority)
      end
      域名TextView.onLongClick=function(v)
        复制(Uri.parse(view.url).authority)
      end

      --print("还没做好")
      分享链接2(view.Title,view.url,list3,关闭对话框)

      w,h=getwh(菜单CardView)
      --上升动画
      --相关参数，请自行手册查询
      --定义动画,500为上升高度。
      yuxuandh3=TranslateAnimation(0,0,-h,0)
      --动画时间，也就是上升动画的快慢
      yuxuandh3.setDuration(120)
      --动画开始执行
      菜单CardView.startAnimation(yuxuandh3);
      --动画结束回调
      --设置动画的属性
      透明动画=AlphaAnimation(0,1)
      透明动画.setDuration(120)--设置动画时间
      透明动画.setFillAfter(true)--设置动画后停留位置
      透明动画.setRepeatCount(0)--设置无限循环
      --绑定动画
      菜单背景FrameLayout.startAnimation(透明动画)